# Generated by Django 4.1.3 on 2024-07-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicos', '0003_genero_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('materials', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
