# Generated by Django 4.1.3 on 2024-07-16 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicos', '0004_cliente_imageentry_delete_alumno_delete_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageentry',
            name='author',
            field=models.CharField(choices=[('Esteban', 'Esteban'), ('Nicolas', 'Nicolas'), ('Juan', 'Juan')], default='Título por defecto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageentry',
            name='title',
            field=models.CharField(default='Título por defecto', max_length=255),
        ),
    ]
