# Generated by Django 4.1.3 on 2024-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicos', '0005_imageentry_author_imageentry_date_imageentry_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='imageentry',
            name='author',
            field=models.CharField(choices=[('Esteban Salas', 'Esteban Salas'), ('Nicolas Bustamante', 'Nicolas Bustamante'), ('Juan Pérez', 'Juan Pérez')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='imageentry',
            name='materials',
        ),
        migrations.AddField(
            model_name='imageentry',
            name='materials',
            field=models.ManyToManyField(related_name='image_entries', to='mecanicos.material'),
        ),
    ]
