# Generated by Django 4.1.3 on 2024-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicos', '0006_material_alter_imageentry_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(choices=[('Ampolleta', 'Ampolleta'), ('mangera', 'mangera'), ('foco delantero', 'foco delantero'), ('pasta', 'pasta'), ('aceite', 'aceite'), ('foco trasero', 'foco trasero')], max_length=255),
        ),
    ]
